### ISSUE TITLE
Transparent faking

### ISSUE THREAD

**Issue by alcalyn** [MomsFriendlyRobotCompany/fake_rpi#1]
Hi,

I could make it work with fake `RPi.GPIO` and `smbus` in my application.

But I can't change all the imports (from `from RPi.GPIO import GPIO` to `from fake_rpi import GPIO`) in my project and all dependencies.

So I found a solution inspired by [this stackoverflow answer](https://stackoverflow.com/questions/5122465/can-i-fake-a-package-or-at-least-a-module-in-python-for-testing-purposes) something that replace the modules by this fake one:

``` python
import sys
import fake_rpi

sys.modules['RPi'] = fake_rpi
sys.modules['smbus'] = fake_rpi

# Then everywhere...
import RPi.GPIO as GPIO
import smbus
```

Then, I don't need to change my project and dependencies imports, I just have to replace modules once in my main file.

It could work if inside the folder `fake_rpi`, there were another modules that reflect the `RPi`, `smbus`... modules

Do you think this way of using `fake_rpi` is relevent ?

**Comment by alcalyn** [comment]
I illustrated in that PR https://github.com/MomsFriendlyRobotCompany/fake_rpi/pull/2 what I mean by a working example with the fake `smbus`.

I wanted to do the same with `RPi.GPIO`, but the import is different and I couldn't understand how to reflect the import style.

**Comment by walchko** [comment]
interesting ... I will take a closer look later at how you did this.

**Comment by alcalyn** [comment]
Hi, I also could reproduce RPi.GPIO import, so I made it work also for GPIO in the same PR.

I updated the example: https://github.com/MomsFriendlyRobotCompany/fake_rpi/pull/2/files#diff-3b5e31446f546cea5285cfd44d32d046R6

**Comment by walchko** [comment]
accepted ... thanks!

**Comment by alcalyn** [comment]
Thank you. I'll see if I can also update Readme
