### ISSUE TITLE
Import errors on Python 3.6 and 3.7

### ISSUE THREAD

**Issue by UyChooTran** [MomsFriendlyRobotCompany/fake_rpi#18]
importlib_metadata needs to be installed when using Python 3.6 and 3.7

It would be helpful to list that as a dependency or insert $ pip install importlib-metadata as a part of the installation.

**Comment by walchko** [comment]
fixed, 0.7.1 published to pypi

**Comment by UyChooTran** [comment]
That works too.
Seems to be working for me without that extra pip import (on Travis)
