### ISSUE TITLE
GPIO.setmode(io.BCM)  Error  name 'io' not defined

### ISSUE THREAD

**Issue by agribot2** [MomsFriendlyRobotCompany/fake_rpi#19]
Hi
Thanks for providing this helpful module.
Unfortunatly ...  
 
The line GPIO.setmode(io.BCM)
Causes the pyton error ;-   name 'io' not defined

( background  ...tested using either python 2.7 or python 3.7, in  Microsoft Visual Studio Community 2019, Version 16.7.4  
  using fake_rpi version 0.6.2 )

**Comment by walchko** [comment]
what line in what file?

**Comment by agribot2** [comment]
On the web page ;- https://github.com/MomsFriendlyRobotCompany/fake_rpi
There are several example sets of code.
One code example on that page is


Usage
To fake RPi.GPIO or smbus, this following code must be executed before your application:

# Replace libraries by fake ones
import sys
import fake_rpi

sys.modules['RPi'] = fake_rpi.RPi     # Fake RPi
sys.modules['RPi.GPIO'] = fake_rpi.RPi.GPIO # Fake GPIO
sys.modules['smbus'] = fake_rpi.smbus # Fake smbus (I2C)
Then you can keep your usual imports in your application:

import RPi.GPIO as GPIO
import smbus

GPIO.setmode(io.BCM) # now use the fake GPIO
b = GPIO.input(21)

sm = smbus.SMBus(1) # now use the fake smbus
b = sm.read_byte_data(0x21, 0x32)  # read in a byte

When I use that code , using Vistual Studio on a windows 10 laptop ...
The line GPIO.setmode(io.BCM) # now use the fake GPIO  
Causes the pyton error ;-    name 'io' not defined

However ... I can resolve that error by changing that line to ;-   GPIO.setmode(GPIO.BCM)  # NOT io.BCM

Is the example code provided on the web page incorrect ? 

or is there something about my configuration ;- using either python 2.7 or python 3.7, in Microsoft Visual Studio Community 2019, Version 16.7.4 , using fake_rpi version 0.6.2  that causes the example code to fail ?

**Comment by Tunneller** [comment]
I believe it is just a typo in the documentation. Change to gpio.BCM and everything is fine. Or at least, you will get past that issue.
